spring.application.name=tj-ai
server.port=9090


#大模型对话中文乱码UTF8编码处理
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8


spring.ai.dashscope.api-key=${tjxt_Aliapikey}
#spring.ai.dashscope.base-url=https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation
spring.ai.dashscope.chat.options.model=qwen-plus